name: PyRS
channels:
- conda-forge
- default
- mantid
dependencies:
- python=3.8
- mantidworkbench
- qtpy
- pyqt =5.12
- pytest
- pytest-cov
- pytest-qt
- uncertainties
- vtk
- flake8
- mypy
- pandas
- types-six
- versioningit
- conda-build
- conda-verify
- setuptools
- pip:
  - check-wheel-contents
