name: PyRS
channels:
- conda-forge
- mantid/label/nightly
dependencies:
- python=3.10
- anaconda-client
- boa
- mantidworkbench>=6.8.20231213
- qtpy
- pip
- pyqt=5.15,<6
- pytest
- pytest-cov
- pytest-qt
- uncertainties
- libarchive=3.5.2
- vtk
- flake8
- mypy
- numpy
- pandas
- types-six
- versioningit
- conda-build
- conda-verify
- setuptools
- pip:
  - check-wheel-contents
